name: Deploy website

inputs:
  debug:
    description: Sets "NODE_ENV" to "debug".
    required: false
    default: false
  repository:
    description: The public public repository to push new website to.
    required: true
  pat-token:
    description: Personal access token to use to clone and push website into target repository.
    required: true

runs:
  using: composite

  steps:
    - uses: thaibault/install-npm-package-dependencies-action@main
      with:
        debug: ${{ inputs.debug }}

    - name: Check out the public website repository.
      uses: actions/checkout@master
      with:
        repository: ${{ inputs.repository }}
        token: ${{ inputs.pat-token }}

    - name: DEBUG0
      run: echo ${{ env.GITHUB_WORKSPACE }} && cd ${{ env.GITHUB_WORKSPACE }} && ls -lha
      shell: bash

    - name: DEBUG1
      run: pwd
      shell: bash

    - name: DEBUG2
      run: cd .. && ls -lha
      shell: bash

    - name: DEBUG3
      run: ls -lha
      shell: bash

    - name: Change Owner of Container Working Directory
      run: chown root:root .
      shell: bash

    #- name: Trigger deployment script.
    #  env:
    #    PUBLIC_REPOSITORY_PATH: ${{ env.GITHUB_WORKSPACE }}
    #  run: yarn run update:website
    #  shell: bash
