name: Deploy website

inputs:
  debug:
    description: Sets "NODE_ENV" to "debug".
    required: false
    default: false
  repository:
    description: The public public repository to push new website to.
    required: true
  pat-token:
    description: Personal access token to use to clone and push website into target repository.
    required: true
  author_name_github:
    description: Github author name to use to clone and push website into target repository.
    required: true
  user_email_github:
    description: Github email address to use to clone and push website into target repository.
    required: true

runs:
  using: composite

  steps:
    - uses: thaibault/install-npm-package-dependencies-action@main
      with:
        debug: ${{ inputs.debug }}

    - name: Check out the public website repository.
      uses: actions/checkout@main
      with:
        repository: ${{ inputs.repository }}
        token: ${{ inputs.pat-token }}
        path: ${{ github.workspace }}/public-repository

    - name: Fix Git Safe Directory
      run: git config --global --add safe.directory "${GITHUB_WORKSPACE}/public-repository"
      shell: bash

    - name: Change Owner of Container Working Directory
      run: chown root:root .
      shell: bash

    - name: TODO
      run: echo JAU+${{ inputs.author_name_github }}+${{ inputs.user_email_github }}
      shell: bash

    - name: Trigger deployment script.
      env:
        PUBLIC_REPOSITORY_PATH: ${{ github.workspace }}/public-repository
        AUTHOR_NAME_GITHUB: ${{ inputs.author_name_github }}
        USER_EMAIL_GITHUB: ${{ inputs.user_email_github }}
      run: yarn run update:website
      shell: bash
